name: linters
on: [push, pull_request]
jobs:
  shellcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v22
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - name: Shellcheck
        run: |
          nix-shell -p shellcheck --run 'shellcheck dicom'
      - name: Formating
        run: |
          nix-shell -p shfmt --run 'if [ `shfmt -s -l dicom | tee /dev/stderr | wc -l` -gt 0 ]; then echo Incorrect formating; exit 1; fi'
